Project_identifier: "Phylogenies_MAGs_genomes"
Project_path: "/home/aiswarya/MAG_analyses/Phylogenies"
Phylo_groups:
 - "bifido"
 - "snod"
 - "entero"
 - "com"
 - "api"
 - "lacto"
 - "bapis"
Genome_info_path: "/home/aiswarya/MAG_analyses/Phylogenies/all_GenomeInfo.tsv"
