Project_identifier: "Phylogenies_MAGs_genomes"
Project_path: "/home/aiswarya/MAG_analyses/Phylogenies"
Phylo_groups:
 - "bapis"
 - "bifido"
 - "firm4"
 - "firm5"
 - "gilli"
 - "snod"
Genome_info_path: "/home/aiswarya/MAG_analyses/Phylogenies/GenomeInfo.csv"
