Project_identifier: "Phylogenies_MAGs_genomes"
Project_path: "/work/FAC/FBM/DMF/pengel/spirit/aprasad/Phylogenies"
Phylo_groups:
 - "bifido"
 - "snod"
 - "entero"
 - "com"
 - "api"
 - "lacto"
 - "bapis"
Genome_info_path: "/work/FAC/FBM/DMF/pengel/spirit/aprasad/Phylogenies/all_GenomeInfo.tsv"
